# Pytorch Tensor Fundamentals

- Pytorch is an open source machine learning and deep learning framework


In [2]:
import torch
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


***

## Tensor

1. Tensors are fundamental building block of machine learning
2. Tensor is kind of multi-dimensional array like numpy array but run on GPU instead.

### Scalar (0-dimensional tensor)

In [3]:
tensor_scalar = torch.tensor(16)
tensor_scalar


tensor(16)

#### Check the dimension of tensor

In [4]:
tensor_scalar.ndim

0

#### Get the number within a tensor (only work for 0-dimensional tensor)

In [5]:
f"Tensor item: {tensor_scalar.item()}"

'Tensor item: 16'

### Vector (1-dimensional tensor)

In [6]:
tensor_vector = torch.tensor([0,3,7,9,1,2,0,7,3,0])

tensor_vector, f"Tensor dimension: {tensor_vector.ndim}"

(tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]), 'Tensor dimension: 1')

#### Retrieve the shape of tensor

In [7]:
f"Shape of tensor vector : {tensor_vector.shape}"

'Shape of tensor vector : torch.Size([10])'

### Matrix (2-dimensional tensor)

In [8]:
TENSOR_MATRIX = torch.tensor([[0,3,7,9,1,2,0,7,3,0],
                              [0,9,8,1,3,2,5,7,9,2],
                              [0,3,7,6,1,1,7,1,4,8]])

TENSOR_MATRIX



tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
        [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
        [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]])

#### Shape of the matrix

In [9]:
f"Shape of the matrix: {TENSOR_MATRIX.shape}"

'Shape of the matrix: torch.Size([3, 10])'

### Tensor (multiple-dimensional tensor)

In [10]:
tensor = torch.tensor([[[16,10,2004],
                        [9,3,1986],
                        [3,12,2007],
                        [20,7,2010],
                        [4,1,2004]]])
tensor

tensor([[[  16,   10, 2004],
         [   9,    3, 1986],
         [   3,   12, 2007],
         [  20,    7, 2010],
         [   4,    1, 2004]]])

#### Tensor shape

In [11]:
f"Tensor shape: {tensor.shape}"

'Tensor shape: torch.Size([1, 5, 3])'

#### Tensor dimension

In [12]:
f"Tensor dim: {tensor.ndim}"

'Tensor dim: 3'

***

## Random Tensor

In [94]:
ran_tensor = torch.rand(size=(224,224,3)) # ([height, width, color_channels])
ran_tensor

tensor([[[0.8818, 0.8782, 0.5274],
         [0.0297, 0.1434, 0.1137],
         [0.6546, 0.0778, 0.9789],
         ...,
         [0.2149, 0.2187, 0.6186],
         [0.9234, 0.3978, 0.9917],
         [0.5657, 0.5665, 0.3220]],

        [[0.6868, 0.8504, 0.2323],
         [0.5756, 0.6202, 0.2531],
         [0.7907, 0.7920, 0.8056],
         ...,
         [0.7767, 0.5080, 0.9974],
         [0.9311, 0.9186, 0.9114],
         [0.2134, 0.7985, 0.4693]],

        [[0.7710, 0.2053, 0.3264],
         [0.6850, 0.7437, 0.1260],
         [0.5273, 0.4716, 0.3857],
         ...,
         [0.0377, 0.9513, 0.8071],
         [0.7844, 0.4371, 0.5309],
         [0.5304, 0.2954, 0.5497]],

        ...,

        [[0.6066, 0.9043, 0.2323],
         [0.7661, 0.0326, 0.0672],
         [0.5854, 0.9981, 0.7584],
         ...,
         [0.4233, 0.3866, 0.3680],
         [0.0923, 0.3519, 0.2337],
         [0.2013, 0.1656, 0.1025]],

        [[0.5125, 0.1353, 0.6573],
         [0.3599, 0.1362, 0.1065],
         [0.

In [14]:
f"Shape of ran tensor : {ran_tensor.shape} and tensor dimension: {ran_tensor.ndim}"

'Shape of ran tensor : torch.Size([224, 224, 3]) and tensor dimension: 3'

### *Shuffle tensor*

***

## Zeros and Ones

In [15]:
zero_tensor = torch.zeros(size=(1,6), dtype=torch.int32)
zero_tensor

tensor([[0, 0, 0, 0, 0, 0]], dtype=torch.int32)

In [16]:
one_tensor = torch.ones(size=(2,4), dtype=torch.int16)
one_tensor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)

## Tensor within a range

In [17]:
range_tensor = torch.arange(2,30, 2) #  torch.arrange(start, end, step)
range_tensor

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Zeros_like and Ones_like

In [18]:
# Turn any tensor into zeros tensor.
zeros_like_tensor = torch.zeros_like(input=range_tensor)

zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Same effect 
zero_tensor = torch.zeros(size=range_tensor.shape, dtype=torch.float32)
zero_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Getting information of a tensor

- shape - What shape is the tensor? (some operations requires specific rules)
- dtype - What datatype are the elements within the tensor stored in
- device - What device is the tensor stored on? (usually GPU or CPU)


In [20]:
f"Shape: {range_tensor.shape}", f"Data type: {range_tensor.dtype}", f"Device: {range_tensor.device}"

('Shape: torch.Size([14])', 'Data type: torch.int64', 'Device: cpu')

***

## Manipulating Tensor (Operations)

- *Scalar Operations*

- *Matrix Operations*


In [21]:
tensor

tensor([[[  16,   10, 2004],
         [   9,    3, 1986],
         [   3,   12, 2007],
         [  20,    7, 2010],
         [   4,    1, 2004]]])

### *Addition*

In [22]:
tensor + 100

tensor([[[ 116,  110, 2104],
         [ 109,  103, 2086],
         [ 103,  112, 2107],
         [ 120,  107, 2110],
         [ 104,  101, 2104]]])

### *Subtraction*

In [23]:
tensor - 100

tensor([[[ -84,  -90, 1904],
         [ -91,  -97, 1886],
         [ -97,  -88, 1907],
         [ -80,  -93, 1910],
         [ -96,  -99, 1904]]])

### *Multiplication*

In [24]:
tensor * 100

tensor([[[  1600,   1000, 200400],
         [   900,    300, 198600],
         [   300,   1200, 200700],
         [  2000,    700, 201000],
         [   400,    100, 200400]]])

### *Division*

In [25]:
tensor / 4

tensor([[[4.0000e+00, 2.5000e+00, 5.0100e+02],
         [2.2500e+00, 7.5000e-01, 4.9650e+02],
         [7.5000e-01, 3.0000e+00, 5.0175e+02],
         [5.0000e+00, 1.7500e+00, 5.0250e+02],
         [1.0000e+00, 2.5000e-01, 5.0100e+02]]])

### *Matrix Multiplication*

Rules for matrix multiplication

1. The **inner dimensions** must match

        (3, 2) @ (3, 2) ->  Won't work
        (2, 3) @ (3, 2) -> Will work
        (3, 2) @ (2, 3) -> Will work

2. The resulting matrix has the shape of the **Outer dimension**
        
        (2, 3) @ (3, 2) = (2, 2)
        (3, 2) @ (2, 3) = (3, 3)



*Note: "**@**" in Python is the symbol for both matrix multiplication notation and for programming syntax*.

Other way to perform matrix multiplication:
- **torch.matmul()**
- **Tensor.matmul()**

*Matrix multiplication like this is also referred to as the **dot product** of two matrices*



In [26]:

tensor_2x3 = torch.rand(size=(2,3))
tensor_3x2 = torch.rand(size=(3,2))

tensor_3x2, "^", tensor_2x3


(tensor([[0.3216, 0.7157],
         [0.0400, 0.8578],
         [0.7680, 0.9590]]),
 '^',
 tensor([[0.0736, 0.8598, 0.7692],
         [0.8741, 0.9378, 0.6995]]))

In [27]:
# (2,3) @ (3,2) -> (2,2)
tensor_2x3 @ tensor_3x2

tensor([[0.6488, 1.5278],
        [0.8559, 2.1008]])

In [28]:
# (3,2) @ (2,3) -> (3,3)
tensor_3x2 @ tensor_2x3

tensor([[0.6492, 0.9477, 0.7480],
        [0.7527, 0.8388, 0.6308],
        [0.8948, 1.5597, 1.2616]])

### *Element-wise multiplication*

-  Suppose **s** and **t** are two vectors of the **same dimension**. Then we use **s ⊙ t** to denote the element-wise product of the two vectors. 

        [1 2] ⊙ [3 4] = [1x3  2x4] = [3 8]      -> Mathematical Notation 
        [1 2] * [3 4] = [1x3  2x4] = [3 8]      -> Programming Syntax

*Element-wise multiplication is sometimes called the **Hadamard product** or **Schur product**, applied the same rule as matrix Addition, Subtraction*

*This rule of same size applied for all kind of tensor*

**Element-wise multiplication != Matrix multiplication**

In [29]:
tensor_vector

tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0])

In [30]:
tensor_vector * tensor_vector

tensor([ 0,  9, 49, 81,  1,  4,  0, 49,  9,  0])

### *Matrix Addition, Subtraction, Division*

**Rule:**
- The matrices are using for these kind of operators must be in the same size(shape)

*These rule are applied for Matrix Subtraction, Division also*

In [31]:
tensor_2x3 + tensor_3x2.T, "^", tensor_2x3 - tensor_3x2.T ,"^", tensor_2x3 / tensor_3x2.T

(tensor([[0.3953, 0.8998, 1.5372],
         [1.5897, 1.7956, 1.6585]]),
 '^',
 tensor([[-0.2480,  0.8198,  0.0011],
         [ 0.1584,  0.0800, -0.2595]]),
 '^',
 tensor([[ 0.2289, 21.4843,  1.0015],
         [ 1.2213,  1.0933,  0.7294]]))

***

## Transpose matrix

### *0-dimensional tensor transpose is deprecated*

### *1-dimensional tensor*

In [32]:
tensor_vector

tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0])

In [33]:
# After transpose => the same as the original => unnecessary to transpose
tensor_vector.T

/tmp/ipykernel_14707/367959955.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647329220/work/aten/src/ATen/native/TensorShape.cpp:3683.)
  tensor_vector.T


tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0])

### *2-dimensional tensor*

In [34]:
TENSOR_MATRIX

tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
        [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
        [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]])

In [35]:
TENSOR_MATRIX.T     # => Prefer using this syntax for matrix => easy to understand and interpret

tensor([[0, 0, 0],
        [3, 9, 3],
        [7, 8, 7],
        [9, 1, 6],
        [1, 3, 1],
        [2, 2, 1],
        [0, 5, 7],
        [7, 7, 1],
        [3, 9, 4],
        [0, 2, 8]])

### *3-dimensional tensor*

**I got it:**

- *transpose mean that you indirectly reshape the matrix or the tensor, but in a simple way, that you just rearrange, swap the dimension of a tensor without redefine it, that's it*

        tensor.transpose(0,1) => swap the 0th dim to the 1th dim => 
        tensor.transpose(0,2) => swap the 0th dim to the 2th dim => tensor.T    (short-hand syntax)
        tensor.transpose(1,2) => swap the 1th dim to the 2th dim => tensor.mT 

*There're much more things to play when we deal with higher multi-dimensional tensors, stay tuned*

In [36]:
tensor, "^", tensor.shape

(tensor([[[  16,   10, 2004],
          [   9,    3, 1986],
          [   3,   12, 2007],
          [  20,    7, 2010],
          [   4,    1, 2004]]]),
 '^',
 torch.Size([1, 5, 3]))

In [37]:
tensor.transpose(0,1).shape, "^",\
tensor.transpose(0,2).shape, "^",\
tensor.transpose(1,2).shape, "^"


(torch.Size([5, 1, 3]),
 '^',
 torch.Size([3, 5, 1]),
 '^',
 torch.Size([1, 3, 5]),
 '^')

***

## Aggregation

- min
- max
- mean
- sum

*Apply for all kind of tensor*

### *Min*

In [38]:
f"Minimum of tensor: {tensor_vector.min()}", tensor_vector

('Minimum of tensor: 0', tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]))

### *Max*

In [39]:
f"Maximum of tensor: {tensor_vector.max()}", tensor_vector

('Maximum of tensor: 9', tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]))

### *Mean*

In [40]:
f"Mean of tensor: {tensor_vector.type(torch.float32).mean()}", tensor_vector

('Mean of tensor: 3.200000047683716', tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]))

### *Sum*

In [41]:
f"Mean of tensor: {tensor_vector.sum()}", tensor_vector

('Mean of tensor: 32', tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]))

***

## Positional Aggregation

- argmax()
- argmin()

*Return the single index value of the max or min value in the tensor has already flatten, regardless of that tensor's dimension*

### *Argmax()*

In [42]:
f"Tensor: {tensor_vector.tolist()} has the maximum value is {tensor_vector.max()} at index {tensor_vector.argmax()}"

'Tensor: [0, 3, 7, 9, 1, 2, 0, 7, 3, 0] has the maximum value is 9 at index 3'

### *Argmin()*

In [43]:
TENSOR_MATRIX

tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
        [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
        [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]])

In [44]:
f"Tensor matrix above has the maximum value is {TENSOR_MATRIX.min()} at index {TENSOR_MATRIX.argmin()}"

'Tensor matrix above has the maximum value is 0 at index 0'

***

## Reshaping

**Rules of thumbs when reshaping tensor**

- *The tensor after reshaped must preserve the total number of elements*

- *View the tensor in the different dimension arrangement*

*Think of it like you flatten it first then you rearrange its dimension as you desired*

In [45]:
TENSOR_MATRIX,    '^',f"Shape: {TENSOR_MATRIX.shape}", '^', f"Total number of elements: {TENSOR_MATRIX.shape.numel()}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([3, 10])',
 '^',
 'Total number of elements: 30')

In [46]:
TENSOR_MATRIX_reshaped = TENSOR_MATRIX.reshape(5,6)

TENSOR_MATRIX_reshaped,    '^',f"Shape: {TENSOR_MATRIX_reshaped.shape}", '^', f"Total number of elements: {TENSOR_MATRIX_reshaped.shape.numel()}"

(tensor([[0, 3, 7, 9, 1, 2],
         [0, 7, 3, 0, 0, 9],
         [8, 1, 3, 2, 5, 7],
         [9, 2, 0, 3, 7, 6],
         [1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([5, 6])',
 '^',
 'Total number of elements: 30')

In [47]:
TENSOR_MATRIX_reshaped = TENSOR_MATRIX.reshape(1,30, )

TENSOR_MATRIX_reshaped,    '^',f"Shape: {TENSOR_MATRIX_reshaped.shape}", '^', f"Total number of elements: {TENSOR_MATRIX_reshaped.shape.numel()}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0, 0, 9, 8, 1, 3, 2, 5, 7, 9, 2, 0, 3, 7, 6,
          1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([1, 30])',
 '^',
 'Total number of elements: 30')

In [48]:
TENSOR_MATRIX_reshaped = TENSOR_MATRIX.reshape(5, 1, 6)

TENSOR_MATRIX_reshaped,    '^',f"Shape: {TENSOR_MATRIX_reshaped.shape}", '^', f"Total number of elements: {TENSOR_MATRIX_reshaped.shape.numel()}"

(tensor([[[0, 3, 7, 9, 1, 2]],
 
         [[0, 7, 3, 0, 0, 9]],
 
         [[8, 1, 3, 2, 5, 7]],
 
         [[9, 2, 0, 3, 7, 6]],
 
         [[1, 1, 7, 1, 4, 8]]]),
 '^',
 'Shape: torch.Size([5, 1, 6])',
 '^',
 'Total number of elements: 30')

***

## Stacking

- *Stacking tensor mean duplicated the tensor on top of itself many times so that the result tensor obviously gain one more dimension (wrapping reasonably)*

In [49]:
TENSOR_MATRIX, "^", f"Shape: {TENSOR_MATRIX.shape}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([3, 10])')

In [50]:
TENSOR_MATRIX_stacked = torch.stack([TENSOR_MATRIX, 
                                     TENSOR_MATRIX,
                                     TENSOR_MATRIX], dim=1) # they're in the same size

TENSOR_MATRIX_stacked, "^", f"Shape: {TENSOR_MATRIX_stacked.shape}"

(tensor([[[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
          [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
          [0, 3, 7, 9, 1, 2, 0, 7, 3, 0]],
 
         [[0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
          [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
          [0, 9, 8, 1, 3, 2, 5, 7, 9, 2]],
 
         [[0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
          [0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
          [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]]),
 '^',
 'Shape: torch.Size([3, 3, 10])')

***

## Concatenating

    torch.cat((tensor_1,... tensor_2,) dim=0, **)

**Key points when perform concatenating tensors:**

- the tensors are using to concatenate must be in the same size

*Find the rule yourself, I'm out*


### *Matrix concatenating*

In [51]:
TENSOR_MATRIX, "^", f"Tensor dimension: {TENSOR_MATRIX.dim()}", "^", f"Tensor shape: {TENSOR_MATRIX.shape}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]),
 '^',
 'Tensor dimension: 2',
 '^',
 'Tensor shape: torch.Size([3, 10])')

*when set the **dim=1** these two tensors is concatenated horizontally*

In [52]:
TENSOR_MATRIX_con = torch.cat((TENSOR_MATRIX, TENSOR_MATRIX, TENSOR_MATRIX), dim=0)
TENSOR_MATRIX_con, "^", f"Shape: {TENSOR_MATRIX_con.shape}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([9, 10])')

*when set the **dim=0** these two tensors above is concatenated vertically*


In [53]:
TENSOR_MATRIX_con = torch.concat((TENSOR_MATRIX, TENSOR_MATRIX,), dim=1)
TENSOR_MATRIX_con, "^", f"Shape: {TENSOR_MATRIX_con.shape}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0, 0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2, 0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8, 0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]),
 '^',
 'Shape: torch.Size([3, 20])')

### *Multi-dimensional Tensor concatenating*

**The rule:**
- The concatenated tensor is computed by adding all the dim of those tensors 

        tensor_2x3x5 concat(dim=0) tensor_2x3x5 = tensor_4x3x5
        tensor_2x3x5 concat(dim=1) tensor_2x3x5 = tensor_2x6x5
        tensor_2x3x5 concat(dim=2) tensor_2x3x5 = tensor_2x3x10
        
*How easy it is*

In [54]:
tensor_2x3x5 = torch.rand(2,3,5)
tensor_2x3x5

tensor([[[0.5779, 0.1591, 0.9498, 0.3779, 0.8012],
         [0.0357, 0.6562, 0.0634, 0.9714, 0.8872],
         [0.8116, 0.0194, 0.1223, 0.5584, 0.3756]],

        [[0.5161, 0.8385, 0.5450, 0.2283, 0.0072],
         [0.3512, 0.7032, 0.4121, 0.2701, 0.9033],
         [0.8857, 0.4125, 0.6010, 0.3538, 0.6253]]])

In [55]:
tensor_4x3x5 = torch.concat((tensor_2x3x5, tensor_2x3x5), dim=0 )
tensor_4x3x5, "^",  f"Shape: {tensor_4x3x5.shape}"

(tensor([[[0.5779, 0.1591, 0.9498, 0.3779, 0.8012],
          [0.0357, 0.6562, 0.0634, 0.9714, 0.8872],
          [0.8116, 0.0194, 0.1223, 0.5584, 0.3756]],
 
         [[0.5161, 0.8385, 0.5450, 0.2283, 0.0072],
          [0.3512, 0.7032, 0.4121, 0.2701, 0.9033],
          [0.8857, 0.4125, 0.6010, 0.3538, 0.6253]],
 
         [[0.5779, 0.1591, 0.9498, 0.3779, 0.8012],
          [0.0357, 0.6562, 0.0634, 0.9714, 0.8872],
          [0.8116, 0.0194, 0.1223, 0.5584, 0.3756]],
 
         [[0.5161, 0.8385, 0.5450, 0.2283, 0.0072],
          [0.3512, 0.7032, 0.4121, 0.2701, 0.9033],
          [0.8857, 0.4125, 0.6010, 0.3538, 0.6253]]]),
 '^',
 'Shape: torch.Size([4, 3, 5])')

In [56]:
tensor_2x6x5 = torch.concat((tensor_2x3x5, tensor_2x3x5), dim=1 )
tensor_2x6x5, "^",  f"Shape: {tensor_2x6x5.shape}"

(tensor([[[0.5779, 0.1591, 0.9498, 0.3779, 0.8012],
          [0.0357, 0.6562, 0.0634, 0.9714, 0.8872],
          [0.8116, 0.0194, 0.1223, 0.5584, 0.3756],
          [0.5779, 0.1591, 0.9498, 0.3779, 0.8012],
          [0.0357, 0.6562, 0.0634, 0.9714, 0.8872],
          [0.8116, 0.0194, 0.1223, 0.5584, 0.3756]],
 
         [[0.5161, 0.8385, 0.5450, 0.2283, 0.0072],
          [0.3512, 0.7032, 0.4121, 0.2701, 0.9033],
          [0.8857, 0.4125, 0.6010, 0.3538, 0.6253],
          [0.5161, 0.8385, 0.5450, 0.2283, 0.0072],
          [0.3512, 0.7032, 0.4121, 0.2701, 0.9033],
          [0.8857, 0.4125, 0.6010, 0.3538, 0.6253]]]),
 '^',
 'Shape: torch.Size([2, 6, 5])')

In [57]:
tensor_4x3x10 = torch.concat((tensor_2x3x5, tensor_2x3x5), dim=2 )
tensor_4x3x10, "^",  f"Shape: {tensor_4x3x10.shape}"

(tensor([[[0.5779, 0.1591, 0.9498, 0.3779, 0.8012, 0.5779, 0.1591, 0.9498,
           0.3779, 0.8012],
          [0.0357, 0.6562, 0.0634, 0.9714, 0.8872, 0.0357, 0.6562, 0.0634,
           0.9714, 0.8872],
          [0.8116, 0.0194, 0.1223, 0.5584, 0.3756, 0.8116, 0.0194, 0.1223,
           0.5584, 0.3756]],
 
         [[0.5161, 0.8385, 0.5450, 0.2283, 0.0072, 0.5161, 0.8385, 0.5450,
           0.2283, 0.0072],
          [0.3512, 0.7032, 0.4121, 0.2701, 0.9033, 0.3512, 0.7032, 0.4121,
           0.2701, 0.9033],
          [0.8857, 0.4125, 0.6010, 0.3538, 0.6253, 0.8857, 0.4125, 0.6010,
           0.3538, 0.6253]]]),
 '^',
 'Shape: torch.Size([2, 3, 10])')

***

## Squeezing

- *How about removing all single dimensions from a tensor?*

***Eg.***

    torch.Size([1, 1, 4, 5, 1]) => squeezed => torch.Size([4, 5])

*Easy to comprehend, right!*



In [58]:
temp_tensor = torch.rand(size=(1,1,4,5,1), dtype=torch.float32) # make an example

temp_tensor,  "^", f"Shape: {temp_tensor.shape}"

(tensor([[[[[0.4947],
            [0.0709],
            [0.6561],
            [0.9767],
            [0.3276]],
 
           [[0.2643],
            [0.3453],
            [0.2028],
            [0.0101],
            [0.3845]],
 
           [[0.1698],
            [0.6623],
            [0.9199],
            [0.2478],
            [0.4083]],
 
           [[0.0742],
            [0.1514],
            [0.5069],
            [0.5581],
            [0.1320]]]]]),
 '^',
 'Shape: torch.Size([1, 1, 4, 5, 1])')

In [59]:
temp_tensor_squeezed = temp_tensor.squeeze()

temp_tensor_squeezed,   "^", f"Shape: {temp_tensor_squeezed.shape}"

(tensor([[0.4947, 0.0709, 0.6561, 0.9767, 0.3276],
         [0.2643, 0.3453, 0.2028, 0.0101, 0.3845],
         [0.1698, 0.6623, 0.9199, 0.2478, 0.4083],
         [0.0742, 0.1514, 0.5069, 0.5581, 0.1320]]),
 '^',
 'Shape: torch.Size([4, 5])')

***

## Indexing

- *indexing values goes outer dimension -> inner dimension (through the square bracket)*

        Using tensor[idx_dim1][idx_dim2][idx_dim3][...] when perform indexing

In [60]:
TENSOR_MATRIX_stacked, "^", f"Shape: {TENSOR_MATRIX_stacked.shape}"

(tensor([[[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
          [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
          [0, 3, 7, 9, 1, 2, 0, 7, 3, 0]],
 
         [[0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
          [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
          [0, 9, 8, 1, 3, 2, 5, 7, 9, 2]],
 
         [[0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
          [0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
          [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]]),
 '^',
 'Shape: torch.Size([3, 3, 10])')

In [61]:
TENSOR_MATRIX_stacked[0], "^", f"Shape: {TENSOR_MATRIX_stacked[0].shape}"

(tensor([[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0]]),
 '^',
 'Shape: torch.Size([3, 10])')

In [62]:
TENSOR_MATRIX_stacked[0][1] , "^", f"Shape: {TENSOR_MATRIX_stacked[0][1].shape}"

(tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]), '^', 'Shape: torch.Size([10])')

In [63]:
TENSOR_MATRIX_stacked[0][1][2] , "^", f"Shape: {TENSOR_MATRIX_stacked[0][1][2].shape}"

(tensor(7), '^', 'Shape: torch.Size([])')

***

## Slicing

- Slicing when we want to slice the tensor in a specific range or dimension

        Using tensor[idx_start_dim1: idx_end_dim1: idx_step_dim1,  idx_start_dim2: idx_end_dim2: idx_step_dim2, ...] when slicing

Note: tensor can be only slice in a finite time, limited by the tensor dimension

If you want to make more slicing, then make it in a new square bracket

In [64]:
TENSOR_MATRIX_stacked

tensor([[[0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0],
         [0, 3, 7, 9, 1, 2, 0, 7, 3, 0]],

        [[0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2],
         [0, 9, 8, 1, 3, 2, 5, 7, 9, 2]],

        [[0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8],
         [0, 3, 7, 6, 1, 1, 7, 1, 4, 8]]])

*trying to internalize this move, you're the one who fucking made it*

In [65]:
TENSOR_MATRIX_stacked[0:2, 0, 1: 5][0:2, 1][1] # limitation of slicing times

tensor(8)

## Tensor vs Numpy

**Using these two method to transform a numpy array into tensor pytorch and vice versa**

    torch.from_numpy(ndarray) :  Numpy array    -> Pytorch Tensor
    torch.Tensor.numpy()      :  Pytorch Tensor -> Numpy array

*Note: the transformation have no affection on the data type itself*



In [66]:
import numpy as np

ndarray = np.array([0,3,7,9,1,2,0,7,3,0])
ndarray, ndarray.dtype

(array([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]), dtype('int64'))

### *ndarray to tensor*

In [67]:
tensor_array = torch.from_numpy(ndarray)
tensor_array, tensor_array.dtype

(tensor([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]), torch.int64)

### *tensor to ndarray*

In [68]:
ndarray = tensor_array.numpy()
ndarray, ndarray.dtype

(array([0, 3, 7, 9, 1, 2, 0, 7, 3, 0]), dtype('int64'))

***

## Reproducibility

In [69]:
# reproducibility with reset RANDOM_SEED
RANDOM_SEED = 16

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

random_tensor_A == random_tensor_B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [70]:
# reproducibility without reset RANDOM_SEED
RANDOM_SEED = 16
torch.manual_seed(seed=RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

***

## Utilizing GPU as computational unit

In [71]:
# Check if cuda was installed on this device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

*If device is cuda that mean Pytorch can see the GPU(Nvidia) on your computer and you can utilize its computational power for good*

#### *device(type=cuda) ~ Nvidia GPU*

In [72]:
tensor, "^", f"Device: {tensor.device}"

(tensor([[[  16,   10, 2004],
          [   9,    3, 1986],
          [   3,   12, 2007],
          [  20,    7, 2010],
          [   4,    1, 2004]]]),
 '^',
 'Device: cpu')

### *Moving tensor to the gpu (if available)*

*Copying the tensor to the gpu*

In [73]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, "^", f"Device: {tensor_on_gpu.device}"

(tensor([[[  16,   10, 2004],
          [   9,    3, 1986],
          [   3,   12, 2007],
          [  20,    7, 2010],
          [   4,    1, 2004]]], device='cuda:0'),
 '^',
 'Device: cuda:0')

### *Moving tensor back to CPU*

*Returning a copy of tensor in gpu to cpu*

In [74]:
tensor_on_cpu = tensor_on_gpu.cpu()

tensor_on_cpu, "^", f"Device: {tensor_on_cpu.device}"

(tensor([[[  16,   10, 2004],
          [   9,    3, 1986],
          [   3,   12, 2007],
          [  20,    7, 2010],
          [   4,    1, 2004]]]),
 '^',
 'Device: cpu')

*The original tensor in gpu stay there the same*

In [75]:
tensor_on_gpu, "^", f"Device: {tensor_on_gpu.device}"

(tensor([[[  16,   10, 2004],
          [   9,    3, 1986],
          [   3,   12, 2007],
          [  20,    7, 2010],
          [   4,    1, 2004]]], device='cuda:0'),
 '^',
 'Device: cuda:0')

***

## Neural network

*Neural nets are full of matrix multiplications and dot products*

The ***torch.nn.Linear()*** module also known as a feed-forward layer or fully connected layer, implement a matrix multiplication between an input matrix **x** and a weights matrix **A**

        
        y = x @ A.T + b

##### ***Where***

- **x** is the input to the layer (deep learning is the stack of layers like ***torch.nn.Linear())*** and other on top of each other
- **A** is the weights matrix created by the layer, this matrix starts out as random numbers that get neural nets learn to better  represents pattern in data
- *.T* is represented for a transposed matrix, because the weights matrix get transposed
- **b** is the bias term used to slightly offset the weights and the input
- **y** is the output 

In [76]:
torch.manual_seed(16)

# Linear layer perform matrix multiplication
linear = torch.nn.Linear(in_features=10,    # in_feature  = matches inner dimension of input matrix
                         out_features=6)   # out feature = describes outer value

x = tensor_vector.type(torch.float32)
output = linear(x)

output, "^", f"Shape: {output.shape}"

(tensor([ 0.7211, -1.5712, -1.6104,  0.6170,  2.7666, -0.3493],
        grad_fn=<ViewBackward0>),
 '^',
 'Shape: torch.Size([6])')

- *input shape = (1,10)* 
- *output shape = (10, 6)*

        (1, 10) * (10,6) = (1,6)

***


## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.


1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
2. Create a random tensor with shape (7, 7).
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
4. Set the random seed to 0 and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

**Extra-curriculum**

    *Spend 1-hour going through the PyTorch basics tutorial (I'd recommend the Quickstart and Tensors sections).
    To learn more on how a tensor can represent data, see this video: What's a tensor?*



In [77]:
1.
2.
tensor_7_7 = torch.rand(size=(7,7))
tensor_7_7

tensor([[0.3663, 0.2344, 0.4978, 0.9769, 0.8070, 0.2074, 0.2312],
        [0.2481, 0.6315, 0.6485, 0.4123, 0.1299, 0.9386, 0.7432],
        [0.4514, 0.7183, 0.9324, 0.3358, 0.7483, 0.0794, 0.9697],
        [0.8907, 0.2126, 0.1475, 0.4472, 0.4347, 0.8528, 0.6217],
        [0.5016, 0.5251, 0.0743, 0.4651, 0.1498, 0.6331, 0.2403],
        [0.6683, 0.7104, 0.2131, 0.8983, 0.2129, 0.9838, 0.7356],
        [0.0420, 0.2532, 0.5681, 0.8978, 0.5465, 0.1709, 0.5687]])

In [78]:
3.
ran_tensor_1_7 = torch.rand(size=(1,7))
ran_tensor_1_7

tensor_7_7 @ ran_tensor_1_7.T


tensor([[2.0542],
        [2.5098],
        [3.3411],
        [2.4096],
        [1.6466],
        [2.8574],
        [1.9666]])

In [79]:
4. 
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

tensor_7_7 = torch.rand(size=(7,7))
ran_tensor_1_7 = torch.rand(size=(1,7))

tensor_7_7 @ ran_tensor_1_7.T



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [80]:
5. 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

tensor_2x3_gpu = torch.rand(size=(2,3), device=device)
tensor_2x3_gpu, "^", tensor_2x3_gpu.device



(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 '^',
 device(type='cuda', index=0))

In [81]:
6. 
tensor_2x3_cpu_ran_f = torch.rand(size=(2,3))
tensor_2x3_cpu_ran_s = torch.rand(size=(2,3))

tensor_2x3_gpu_ran_f = tensor_2x3_cpu_ran_f.to(device=device)
tensor_2x3_gpu_ran_s = tensor_2x3_cpu_ran_s.to(device=device)

tensor_2x3_gpu_ran_f, "^", tensor_2x3_gpu_ran_f.device

(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 '^',
 device(type='cuda', index=0))

In [82]:
7. 
tensor_result = tensor_2x3_gpu_ran_f @ tensor_2x3_gpu_ran_s.T
tensor_result

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='cuda:0')

In [83]:
8. 
tensor_result.min()

tensor(0.3129, device='cuda:0')

In [84]:
9.1
tensor_result.max()

tensor(1.0651, device='cuda:0')

In [85]:
9.2 
tensor_result.mean()

tensor(0.6761, device='cuda:0')

In [86]:
10. 
tensor_ran = torch.randn(size=(1,1,1,10))
tensor_ran

tensor([[[[-2.2188,  0.2590, -1.0297, -0.5008,  0.2734, -0.9181, -0.0404,
            0.2881, -0.0075, -0.9145]]]])

In [87]:
tensor_ran_squeezed = tensor_ran.squeeze()
tensor_ran_squeezed

tensor([-2.2188,  0.2590, -1.0297, -0.5008,  0.2734, -0.9181, -0.0404,  0.2881,
        -0.0075, -0.9145])

In [88]:
tensor_ran_squeezed.shape

torch.Size([10])